### ISSUE TITLE
Breakdown of drug spending by use(s)/purpose(s)

### ISSUE THREAD

**Issue by mattgawarecki** [Data4Democracy/drug-spending#15]
# Task
Analyze Medicare Part D spending to build an understanding of the most treated conditions, as well as what's the most expensive to treat.

This is your chance to break out the tables, graphs, and charts!

# How this will help
If we can get an idea of what Part D is being used to treat, we can do further exploration to find ways of reducing cost and improving overall quality of care.

**Comment by dhuppenkothen** [comment]
I'd like to take a stab at this over the coming few days, unless that would duplicate someone else's work?

**Comment by mattgawarecki** [comment]
Go for it! I don't think you'll be duplicating anything. Even if you do,
though, that's the kind of thing that sparks discussion and builds great
ideas! Make sure to assign the issue to yourself, and don't forget to shout
if you run into problems! :+1:

On Feb 1, 2017 18:38, "Daniela Huppenkothen" <notifications@github.com>
wrote:

I'd like to take a stab at this over the coming few days, unless that would
duplicate someone else's work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Data4Democracy/drug-spending/issues/15#issuecomment-276830023>,
or mute the thread

**Comment by jenniferthompson** [comment]
Agreed! I think this will be hard to finalize till we wrap up [issue 6](https://github.com/Data4Democracy/drug-spending/issues/6), but it can definitely get worked on in the meantime!

**Comment by dhuppenkothen** [comment]
Thanks! It doesn't look like I can actually assign the issue to myself. "Assignees" is greyed out for me. Could one of you assign me?

@jenniferthompson I realized that, too, last night. I'm currently hacking my way through a (perhaps temporary) solution. Not sure yet whether it'll work; let's see.

**Comment by mattgawarecki** [comment]
@dhuppenkothen I'll work on getting you assigned to the issue. I think we need to get you officially added to the D4D organization to make that happen :-) Will update when I know more, and/or when it's taken care of.

**Comment by mattgawarecki** [comment]
You should now have an invite to the org -- whenever you accept, let me know and I'll officially assign the issue to you. :-)

Remember to fork the repo into your own account first, then do your work there. When you're finished, submit a pull request ("PR") to this repo and we'll review/merge it. Thanks so much for pitching in!

**Comment by jenniferthompson** [comment]
All set @dhuppenkothen!

**Comment by dhuppenkothen** [comment]
Thanks, @jenniferthompson

**Comment by jenniferthompson** [comment]
@dhuppenkothen Do you have a vision in mind for what you want to do here? In the process of writing up what we're working on, I'm wondering if this and [issue 7](https://github.com/Data4Democracy/drug-spending/issues/7) are basically getting at the same thing (Issue 7 is pretty vague and was added awhile back, before we started to get rolling on organization). Since you and I are assigned to each one, I think we should either combine forces (which may mean I hand it over to you!) or differentiate what we're working on, whichever makes more sense. What do you think?

**Comment by dhuppenkothen** [comment]
@jenniferthompson Yes, we should! My hope for this issue was to explore the data and proto-type informative and useful visualizations (for some yet-to-be-determined definition of "informative" and "useful"). It may end up that these visualizations will have an interactive component, in which case they might tie in really well with the Dashboard? 

At this stage, though, my goal is to figure out what's in the data, and how to best display it in 2D. Once we've got that, it probably shouldn't be that hard to either re-code the figures in R and stick them into the Dashboard. Does that seem like a reasonable approach?

I was also going to look at your conceptual drawings to guide some of the initial ideas I have for visualization. :)

**Comment by jenniferthompson** [comment]
@dhuppenkothen Definitely reasonable! Yeah, I think a combination of static and interactive visualizations could work really well for this.

How about I focus on getting things really well organized (repo structure, data dictionaries) for the next few days while you dive deep into this, and once you've got your plan in mind we can talk about specifics? I'm open to adding to the current dashboard or developing a new one (or other vis type), whatever gets the message across best!

**Comment by dhuppenkothen** [comment]
Yes, that sounds good.

**Comment by selahlynch** [comment]
Hey, I'd love to help with this task also.  Any chance you could add a link some of the relevant datasets to be used.  I'm having some difficulty figuring out what they might be.
PS... I pledge to do some data cleaning/grunt work as well

**Comment by jenniferthompson** [comment]
@selahlynch All our datasets are in our [repo on data.world](https://data.world/data4democracy/drug-spending) - so far most of the work has been with the CMS Medicare Part D data (`spending-201x` files). Not sure what @dhuppenkothen has going on so far!

**Comment by dhuppenkothen** [comment]
I haven't used any data sets from `data.world`, as far as I know. The `read_data.py` does all the data reading for what I've been doing so far, but maybe some of those data sets should go up on data.world?

**Comment by jenniferthompson** [comment]
@dhuppenkothen Looking through `read_data.py` - yes, it would be excellent for the prescription drug profiles and RxNorm data to get on data.world (and any other datasets I'm missing). Then non-Pythoners can use it too! That would be really helpful.

**Comment by dhuppenkothen** [comment]
Could you perhaps open an issue and attach it to me? Then I'll get on that after work tonight.

**Comment by jenniferthompson** [comment]
@dhuppenkothen yep, I was already on it :) done!

**Comment by franckjay** [comment]
Hi all, I can try and help with the classification of drugs by use. I had a thought that we could do a Wikipedia scrape for each drug, looking for keywords?

**Comment by darya-akimova** [comment]
Closing in order to restructure the issues and to change project scope.
