### ISSUE TITLE
Investigate new data source: Chronic Conditions Data Warehouse

### ISSUE THREAD

**Issue by mattgawarecki** [Data4Democracy/drug-spending#9]
# Before you continue
**NOTE:** We believe this website is only reachable from a United States IP. If you're working outside the US, you may not be able to work on this issue.

# Task
The Centers for Medicare and Medicaid Services have another website that contains all sorts of information geared toward reducing spending on chronic diseases and conditions. Explore the [Chronic Conditions Data Warehouse website](https://ccwdata.org/web/guest/about-ccw) and investigate any public data sets to see if they could help us put together interesting new data analyses.

# How this will help
Sourcing new data that's related to Medicare drug spending -- especially different ways of looking at and categorizing spending -- will give our team the tools they need to build useful insights that people will want to see.

# What we want to get out of this
To keep a record of the information you find, we'd like a short write-up in this issue thread explaining any available data sets that might be useful to us.

**Comment by sgalletta213** [comment]
**Summary:** There is some chronic condition data that may be helpful.  Other than that, this source contains several free tables that are likely too small to be helpful, and several comprehensive but expensive data sets ($1,000 - $20,000 per data set per year).

**Chronic condition data:** The [Condition Categories page](https://ccwdata.org/web/guest/condition-categories) contains a PDF listing condition categories, Reference Period, Valid ICD-9/CPT4/HCPCS Codes, and Number / Type of Claims to Qualify.  If we're looking to create a table chronic conditions to different codes/criteria, this could be helpful, though I imagine there's a better dataset somewhere out there. Especially since this doesn't contain any drug data.

**Free data sets:** These can be found on the toolbar at [Medicare Data > Medicare Tables & Reports](https://ccwdata.org/web/guest/medicare-tables-reports).  These are summary tables where each row breaks out part of a population (e.g. male vs. female, age brackets), or metrics for Medicare Advantage Part D on different summary levels (e.g. average annual cost per beneficiary, percentage of beneficiaries with/without coverage). We could refer to this data in some way, but have no way of slicing it differently than they already have.

**Paid data sets:** [Data Dictionaries](https://ccwdata.org/web/guest/data-dictionaries) are available for these, as well as a [pricing tool](https://ccwdata.org/web/guest/pricing/data-pricing).  This data contains patient, provider, drug, and plan information on a granular level.  It seems excellent, but it doesn't seem like there's a way to get it for free. It might be worth a shot to contact them? I'm willing to help draft an email if we want to try that route.

**Comment by jenniferthompson** [comment]
This is a great summary @sgalletta213!

Oh man I got so excited - it looks like Medicare has **claim-level data** with encrypted patient IDs!! ...except the price quote for just Part D drug events is $160,000 (I think $20,000/year). HA. Still, an email never hurt anyone! Currently only goes through 2013.

**Comment by sgalletta213** [comment]
Agreed that an email can't hurt!

Poking around CMS this morning, and found that there is some data available for free at [https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/BSAPUFS/BSA_PDE_PUF.html](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/BSAPUFS/BSA_PDE_PUF.html)

It's a claim-level drug spend data from 5% random sample of all Medicare beneficiaries in 2008. It contains patient age/gender, drug cost (total and patient paid), and drug information like name, strength, class, etc.  

Also, the data dictionary there might provide more insight into the 'hcpcs_description' column of the part B spend data, since that column actually looks like a concatenation of drug name, strength, dose dorm, etc. Planning on looking more into that later.

**Comment by Guilhermeslucas** [comment]
Is the ccw site down?

**Comment by mattgawarecki** [comment]
@Guilhermeslucas I'm able to get to it from my machine. Are you unable to load https://ccwdata.org/web/guest/about-ccw ?

**Comment by Guilhermeslucas** [comment]
No :/ Is there region restriction, something like that, since i'm trying to connect from brazil?

**Comment by jenniferthompson** [comment]
Looks like this site is only available in the US, unfortunately; people from Canada and Mexico were also unable to access it.

**Comment by mattgawarecki** [comment]
I think @sgalletta213 gave us exactly the information we were after for this ticket. Closing! 👍
